### ISSUE TITLE
TypeScript error when passing enzymeToJson to setSerializers

### ISSUE THREAD

**Issue by simonsmith** [jest-community/snapshot-diff#108]
Hello, here is my setup code:

**test-setup.ts**
```ts
import * as snapshotDiff from 'snapshot-diff';

// This is the same function exposed in `enzyme-to-json/serializer' as per README
import { createSerializer } from 'enzyme-to-json'; 

const enzymeToJsonSerializer = createSerializer();
snapshotDiff.setSerializers([enzymeToJsonSerializer]);
```

This produces the following error:

```bash
error TS2741: Property 'diffOptions' is missing in type 'JestSerializer' but required in type 'Serializer'.
```

This seems like a mismatch between the [`Serializer`](https://github.com/jest-community/snapshot-diff/blob/652ce486793f874313541b9af9923c16503ddbfa/index.d.ts#L26-L30) type in this repository and the [`JestSerializer`](https://github.com/adriantoine/enzyme-to-json/blob/master/index.d.ts#L22-L25) type from `enzyme-to-json`.

My understanding is that a serializer should only have two required properties (`print` and `test`) so perhaps `diffOptions` needs to be optional? Note that it appears the source code expects [it to be optional already](https://github.com/jest-community/snapshot-diff/blob/652ce486793f874313541b9af9923c16503ddbfa/src/index.js#L43-L45)

If I try to make that change I get:

```bash
 error TS2322: Type 'JestSerializer' is not assignable to type 'Serializer'.
  Types of property 'print' are incompatible.
    Type '(CommonWrapper: CommonWrapper<{}, {}, Component<{}, {}, any>>, serializer: JestSerializer) => Json' is not assignable to type '(value: any, _serializer?: Function | undefined) => string'.
      Types of parameters 'serializer' and '_serializer' are incompatible.
        Type 'Function | undefined' is not assignable to type 'JestSerializer'.
          Type 'undefined' is not assignable to type 'JestSerializer'.
```

Let me know if I can provide further debugging help, thanks

**Comment by thymikee** [comment]
cc @alistairjcbrown

**Comment by alistairjcbrown** [comment]
@simonsmith Definitely - `diffOptions` is non-standard and so is optional in the code; it should be optional in the type declaration too 👍 I'll get a PR up with this updated

**Comment by alistairjcbrown** [comment]
@simonsmith PR is up - could you take a look and see if that solves the issue?
Typescript isn't something I've used a lot, but spinning up a "create react app" with the typescript template, the changes in the PR to appease the errors.

**Comment by simonsmith** [comment]
@alistairjcbrown Working fine now. Thank you for the rapid PR! 👍
