### ISSUE TITLE
`0.8.0` has ansi escape codes

### ISSUE THREAD

**Issue by SimenB** [jest-community/snapshot-diff#129]
![image](https://user-images.githubusercontent.com/1404810/81300553-1b7eee00-9078-11ea-8543-bc73a653bfbc.png)

I don't think we want this?

Makes for a very weird diff when seeing it in a terminal which respects these characters
![image](https://user-images.githubusercontent.com/1404810/81300638-34879f00-9078-11ea-8291-ebbaa4f68415.png)

**Comment by alistairjcbrown** [comment]
@SimenB You beat me by a couple of minutes! 😁(#130) - looks like it's because these colors aren't controlled by the passed options in `jest-diff`? - https://github.com/facebook/jest/blob/4bd3d4a05999170f423f7050d4e0537648499e88/packages/jest-diff/src/constants.ts#L10-L11

**Comment by SimenB** [comment]
@alistairjcbrown PR to Jest so it respects that option is very much welcome 🙂 

/cc @pedrottimark

**Comment by alistairjcbrown** [comment]
PR up against the Jest repo: https://github.com/facebook/jest/pull/9997

**Comment by SimenB** [comment]
26.1.0 out
