### ISSUE TITLE
"No visual difference" message outputting with color

### ISSUE THREAD

**Issue by alistairjcbrown** [jest-community/snapshot-diff#130]
This is more to note the regression than an issue to can be solved in this repo, other than rolling back the PR - looks like some of the diff output messages aren't controlled by the color options - https://github.com/facebook/jest/blob/4bd3d4a05999170f423f7050d4e0537648499e88/packages/jest-diff/src/constants.ts#L10-L11
`jest-diff` is using `chalk.dim` directly, rather than making use of the `commonColor` option which we're turning off when color is set to `false` (from PR #123).

The issue I'm seeing after upgrading is that we're getting a diff with color codes when running Jest normally (no colors when running `CI=true`)
![image](https://user-images.githubusercontent.com/635903/81300972-5846e700-9070-11ea-8428-5a913473982d.png)

**Comment by thymikee** [comment]
Sounds like something that should be fixed upstream. Mind sending a PR?

**Comment by thymikee** [comment]
Closing this in favor of #129 :)
