### ISSUE TITLE
Support react shallow render.

### ISSUE THREAD

**Issue by bogdan-zaharia-hs** [jest-community/snapshot-diff#18]
I usually write the snapshot tests using enzyme shallow render:
```js
it('matches snapshot', () => {
  const shallowNode = shallow(<Component />).getNode();
  expect(shallowNode).toMatchSnapshot();
});
```

I would like to keep this approach when having diffs. However, I get fully  rendered components when I do:
```js
it('matches diff snapshot', () => {
  const firstShallowNode = shallow(<Component />).getNode();
  const secondShallowNode = shallow(<Component selected />).getNode();
  expect(firstShallowNode).toMatchDiffSnapshot(secondShallowNode)
});
```

That's because [`.getNode`](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/getNode.md) also returns a React Component so the diff will choose the [react diff path](https://github.com/jest-community/snapshot-diff/blob/cd43afe7081bebd05a1514f360046928edb649d4/src/index.js#L61)

I'm not sure what would be the solution for this. I've modified the code to ignore the [Component check statement](https://github.com/jest-community/snapshot-diff/blob/cd43afe7081bebd05a1514f360046928edb649d4/src/index.js#L34) and it works fine with [diffStrings](https://github.com/jest-community/snapshot-diff/blob/cd43afe7081bebd05a1514f360046928edb649d4/src/index.js#L52).

**Comment by thymikee** [comment]
This should be as easy as importing ReactTestComponent from pretty-format plugins [here](https://github.com/jest-community/snapshot-diff/blob/master/src/index.js#L9) and pass it to pretty-format config (also adjusting the `test` function). Can you try it?

**Comment by bogdan-zaharia-hs** [comment]
That's not actually solving the issue.

I'll give a more complete example to illustrate my use-case:
```js
describe('snapshot-diff tests', () => {
  const Bar = () => <span>inside Bar</span>;
  const Foo = ({ text = 'none' }) => <div><Bar /><span>{text}</span></div>;

  it('diffs react components', () => {
    const shallowNode = component => shallow(component).getNode();

    const base = <Foo />;
    const withText = <Foo text="something" />;

    expect(shallowNode(base)).toMatchDiffSnapshot(shallowNode(withText), {
      aAnnotation: 'base',
      bAnnotation: 'with text',
    });
  });
});
```

Running this yield the following snapshot:
```diff
Snapshot Diff:
- <div><Bar /><span>none</span></div>
+ <div><Bar /><span>something</span></div>

  <div>
    <span>
      inside Bar
    </span>
    <span>
-     none
+     something
    </span>
  </div>
`;
```

What I would like to get is:

```diff
Snapshot Diff:
- base
+ with text

  <div>
    <Bar />
    <span>
-     none
+     something
    </span>
  </div>
`;
```

That could be done by giving the user the choice of rendering for React Components, instead of using `react-test-renderer`:
- The easiest and most flexible way would be to just use `diffStrings` for everything, and choose `react-test-renderer` or `shallow` in the client code.
- Another option would be to add rendering options for react components.

**Comment by agrinko** [comment]
Faced the same issue. Are the any updates or workarounds here?
