### ISSUE TITLE
Remove peer dependency on `react-test-renderer`

### ISSUE THREAD

**Issue by SimenB** [jest-community/snapshot-diff#20]
I don't use React in my project, but I get a noisy peer dep warning from both npm and yarn when installing this module.

As it's optional, do you think you could drop it as a peer dep?

**Comment by thymikee** [comment]
I'm supportive to that change. I'll tag it as a `good first issue` 

Note to implementer: 
The change requires us to put `react-test-renderer` call in a try/catch and throw some useful error when user tries to use it. We also need a test.
