### ISSUE TITLE
snapshotDiff between two single line strings output null

### ISSUE THREAD

**Issue by allotrop3** [jest-community/snapshot-diff#22]
### Code:
`expect(snapshotDiff("foo", "bar")).toMatchSnapshot();`

### Result:
```
Received value
    Snapshot Diff:
    null
```
It seems adding a new line to the end of both arguments results in a valid snapshot diff. 

### Code

`expect(snapshotDiff("foo" + "\n", "bar" + "\n")).toMatchSnapshot();`

### Result
```
Received value
    Snapshot Diff:
    - First value
    + Second value

    - foo
    + bar
```

**Comment by thymikee** [comment]
Hm, maybe we should add the newline implicitly if there's none? I'm not sure why it doesn't work in general though, anyone mind investigating?

**Comment by pedrottimark** [comment]
Let’s see if it works correctly after https://github.com/jest-community/snapshot-diff/pull/21 because of https://github.com/facebook/jest/pull/4520
