### ISSUE TITLE
Release the next version

### ISSUE THREAD

**Issue by sergei-startsev** [jest-community/snapshot-diff#29]
The published `0.2.2` version relies on `jest` test releases:
```json
//package.json
...
"jest-diff": "test",
"jest-snapshot": "test"
```
It was recently fixed in #21, could you please release a new version to avoid loading beta dependencies - at the moment you have to adjust dependencies manually each time when you add/update a package.

**Comment by thymikee** [comment]
Released 0.3.0 :)
