### ISSUE TITLE
Support custom snapshot serializers on diff inputs

### ISSUE THREAD

**Issue by motiz88** [jest-community/snapshot-diff#30]
My exact use case for this involves migrating from `react-test-renderer` to `enzyme.mount` - the former is natively supported by `pretty-format` while the latter ships with a custom serializer.

Would it make sense for `snapshot-diff` to support an API similar to [`expect.addSnapshotSerializer`](https://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer)? Maybe with a slightly more hygienic twist:

```js
import snapshotDiff from "snapshotDiff";
import enzymeToJson from "enzyme-to-json/serializer";

const diff = snapshotDiff.withSerializers([enzymeToJson]);
diff(a, b); // Runs `a` and `b` through the given serializers before diffing
```

I'm happy to put together a PR for this over the next few days.

**Comment by thymikee** [comment]
Happy to review, seems like a handy feature. Serializers are just pretty-format plugins, so hopefully this will be pretty straight-forward to implement.

@SimenB @pedrottimark are you ok with the API proposal? I thought about `snapshotDiff.[use/add]Plugins([...])` or `snapshotDiff.[use/add]Serializers([...])`. But I like `.withSerializers()` too

**Comment by SimenB** [comment]
Yeah, that sounds good!

**Comment by siebigteroth** [comment]
Any updates on this? :-)
