### ISSUE TITLE
Consider removing React rendering behaviour altogether

### ISSUE THREAD

**Issue by motiz88** [jest-community/snapshot-diff#31]
Questions following #26 and in relation to #30 which I'm currently working on:

Is `pretty-format`'s [React element plugin](https://github.com/facebook/jest/blob/master/packages/pretty-format/src/plugins/react_element.js) not sufficient? Why do we need to actually render components? Or to put it another way, why diverge from `.toMatchSnapshot()`'s behaviour? I would definitely prefer a (semver-major) change to remove this logic.

**Comment by thymikee** [comment]
The main reason we do this, was to get rid of tedious `renderer.create().toJSON()` part, and make it as easy to snapshot components as possible. You should still be able to feed `snapshot-diff` with code like this, if you want consistency with regular snapshots.

**Comment by motiz88** [comment]
I would question the ergonomics of this for someone coming from Jest. It doesn't satisfy the principle of least surprise, IMHO. Especially if over time we want this to have more Jest-like features, e.g. #30.

In my ideal world, refactoring between regular snapshots and diff snapshots should be a no-brainer, as if this was a core Jest API*:

```js
expect(a).toMatchSnapshot();
expect(b).toMatchSnapshot();
// ↑ ↓
expect(snapshotDiff(a, b)).toMatchSnapshot();
```

Except currently, if `a` and `b` are React elements, fundamentally different things happen.

The rendering behaviour can be migrated to an opt-in serializer with #30, so there's an upgrade path for users currently relying on it (which is not everyone - #20).

--- 

\* To the point where, if there was a hygienic way for us to just reuse Jest's config for #30, I would have preferred that btw - but that's off-topic here.

**Comment by thymikee** [comment]
You've got the point. Ideas how can we support both use cases? We should be able to support both use cases
