### ISSUE TITLE
Support snapshot testName in toMatchDiffSnapshot

### ISSUE THREAD

**Issue by NullMDR** [jest-community/snapshot-diff#56]
https://github.com/jest-community/snapshot-diff/blob/447dea40684e620ef21fa412589fe6365a9d4b1d/src/index.js#L94

Could we pass argument testName here?

**Comment by thymikee** [comment]
What's your use case?

**Comment by NullMDR** [comment]
Oh I see I could annotate the snapshot with aAnnotation and bAnnotation. But it could be nice if the testName could be set and shown in .snap file.

**Comment by NullMDR** [comment]
https://jestjs.io/docs/en/snapshot-testing#3-use-descriptive-snapshot-names
https://jestjs.io/docs/en/expect#tomatchsnapshotpropertymatchers-snapshotname

I mean the `snapshotName` argument

**Comment by thymikee** [comment]
Yea that makes sense
