### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nemes-zoltan** [jest-community/snapshot-diff#67]
Hello,

Is there anyway to add some support for typescript? At the moment I need to add `@ts-ignore` so typescript does not complain about `toMatchDiffSnapshot` not existing.

Example:
```
// @ts-ignore
expect(subject.toJSON()).toMatchDiffSnapshot(
      subject2.toJSON()
);
```

Exact typescript error:
`Property 'toMatchDiffSnapshot' does not exist on type 'Matchers<ReactTestRendererJSON | null`

**Comment by thymikee** [comment]
It should be there, see https://github.com/jest-community/snapshot-diff/blob/master/index.d.t
If there's anything wrong with it feel free to send PR with a fix :)

**Comment by nemes-zoltan** [comment]
I don't know how I missed that, thanks :). 

Is there a way to add the typescript definitions globally or, we need to `import 'snapshot-diff';` on each test spec where we want to use the library?

**Comment by thymikee** [comment]
See the docs on that :) https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html
Closing, as this is not a library issue

**Comment by krisdover** [comment]
> See the docs on that :) https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html
> Closing, as this is not a library issue

An example of how to set this up in the documentation would have been helpful.

**Comment by dva** [comment]
@nemes-zoltan you could extend your tsconfig.json `compilerOptions` with `"types": [..., "snapshot-diff"]`

**Comment by krisdover** [comment]
@dva `"types": [..., "snapshot-diff"]` will [disable automatic type inclusion](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types). Subsequent to your response I discovered all that's needed is an import of *snapshot-diff* and the typescript compiler will be able to locate the typings, so I've changed my `setupTests.ts` to:

```
import 'snapshot-diff';
import 'snapshot-diff/extend-expect';
```
