### ISSUE TITLE
Add ability to suppress line numbers from diff

### ISSUE THREAD

**Issue by ericbiewener** [jest-community/snapshot-diff#69]
When diffing component state, I get something that looks like this because only this single line changed in the dom:

```
@@ -89,1 +89,1 @@
-                   class="MuiSelect-root-180 bold red-500"
+                   class="MuiSelect-root-230 bold tp-green-500"
```

That's great! But if I modify an unrelated part of the component that results in additional lines of DOM before the class name change that I'm actually concerned about, the diff breaks because the `@@ -89,1 +89,1 @@` line number may have become `@@ -93,1 +93,1 @@`.

Can we add an option to suppress the line numbers?

**Comment by thymikee** [comment]
The patchmarks (`@@ -93,1 +93,1 @@`) come directly from `jest-diff`. I think we could introduce an option to strip them, why not! Can you make it happen? 😃

**Comment by ericbiewener** [comment]
I'll take a whack at it in the next couple of days 👍

**Comment by thymikee** [comment]
Awesome!
