### ISSUE TITLE
Set the default options globally

### ISSUE THREAD

**Issue by levsero** [jest-community/snapshot-diff#70]
Is there any way to set custom default values globally (where it can be set in a `beforeAll` or in the jest setup) so you don't need to add the options into every `snapshotDiff` call? (eg. Want to have 0 context lines as the default.)

**Comment by thymikee** [comment]
Yes, it's just a function so feel free to pass it some defaults and re-export it:
```js
// testHelpers.js
import snapshotDiff from 'snapshot-diff';

const snapDiff = (a, b, options) => {
  return snapshotdDiff(a, b, {...defaults, ...options});
}

export {snapDiff}
```
