### ISSUE TITLE
Invariant Violation: You should not use <Route> or withRouter() outside a <Router>

### ISSUE THREAD

**Issue by wan54** [jest-community/snapshot-diff#78]
Using enzyme shallow renderer:

```
Invariant Violation: You should not use <Route> or withRouter() outside a <Router>

      71 |
    > 72 | 				expect(snapshotDiff(loading, loaded)).toMatchSnapshot();
         | 				       ^
```

The error does not occur when using the default `toMatchSnapshot()`

**Comment by thymikee** [comment]
We've recently added support for custom serializers, please try it: https://github.com/jest-community/snapshot-diff#custom-serializers
