### ISSUE TITLE
Line Numbers for Differences Failing Test Unnecessarily

### ISSUE THREAD

**Issue by ReshmiCode** [jest-community/snapshot-diff#82]
If I edit some irrelevant data, some lines are added to the snapshot and the snapshot diff test fails because the lines of the differences, for example,
`@@ -7,30 +7,30 @@`
are changed but nothing else. Are these lines really necessary?

**Comment by thymikee** [comment]
You'll find `stablePatchmarks` helpful in this case 🙂: https://github.com/jest-community/snapshot-diff#options
